#include <wgd/index.h>

using namespace wgd::ix;

namespace wgd {
	namespace ix {
	cadence::doste::OID BASEIMPORT position;
	cadence::doste::OID BASEIMPORT orientation;
	cadence::doste::OID BASEIMPORT direction;
	cadence::doste::OID BASEIMPORT changed;
	cadence::doste::OID BASEIMPORT material;
	cadence::doste::OID BASEIMPORT materials;		
	cadence::doste::OID BASEIMPORT model;
	cadence::doste::OID BASEIMPORT models;
	cadence::doste::OID BASEIMPORT animationset;
	cadence::doste::OID BASEIMPORT animations;
	cadence::doste::OID BASEIMPORT animated;
	cadence::doste::OID BASEIMPORT animation;		
	cadence::doste::OID BASEIMPORT transformed;
	cadence::doste::OID BASEIMPORT transition;
	cadence::doste::OID BASEIMPORT meshes;
	cadence::doste::OID BASEIMPORT morphs;
	cadence::doste::OID BASEIMPORT morph;
	cadence::doste::OID BASEIMPORT root;
	cadence::doste::OID BASEIMPORT bones;
	cadence::doste::OID BASEIMPORT animset;
	cadence::doste::OID BASEIMPORT start;
	cadence::doste::OID BASEIMPORT end;
	cadence::doste::OID BASEIMPORT fps;
	cadence::doste::OID BASEIMPORT loop;
	cadence::doste::OID BASEIMPORT next;
	cadence::doste::OID BASEIMPORT solid;
	cadence::doste::OID BASEIMPORT mode;
	
	cadence::doste::OID BASEIMPORT debug;
	
	cadence::doste::OID BASEIMPORT x;
	cadence::doste::OID BASEIMPORT y;
	cadence::doste::OID BASEIMPORT z;
	cadence::doste::OID BASEIMPORT w;
	cadence::doste::OID BASEIMPORT r;
	cadence::doste::OID BASEIMPORT g;
	cadence::doste::OID BASEIMPORT b;
	cadence::doste::OID BASEIMPORT a;
	cadence::doste::OID BASEIMPORT sx;
	cadence::doste::OID BASEIMPORT sy;
	cadence::doste::OID BASEIMPORT sz;
	cadence::doste::OID BASEIMPORT pitch;
	cadence::doste::OID BASEIMPORT yaw;
	cadence::doste::OID BASEIMPORT roll;
	
	cadence::doste::OID BASEIMPORT console;
	cadence::doste::OID BASEIMPORT lines;
	cadence::doste::OID BASEIMPORT visible;
	cadence::doste::OID BASEIMPORT showdebug;
	cadence::doste::OID BASEIMPORT font;
	cadence::doste::OID BASEIMPORT bgcolour;
	cadence::doste::OID BASEIMPORT text;
	
	cadence::doste::OID BASEIMPORT ambient;
	cadence::doste::OID BASEIMPORT specular;
	cadence::doste::OID BASEIMPORT diffuse;
	cadence::doste::OID BASEIMPORT emission;
	cadence::doste::OID BASEIMPORT directional;
	cadence::doste::OID BASEIMPORT linear;
	cadence::doste::OID BASEIMPORT quadratic;
	cadence::doste::OID BASEIMPORT enabled;
	cadence::doste::OID BASEIMPORT lights;
	
	cadence::doste::OID BASEIMPORT size;
	cadence::doste::OID BASEIMPORT name;
	cadence::doste::OID BASEIMPORT bold;
	cadence::doste::OID BASEIMPORT fonts;
	
	cadence::doste::OID BASEIMPORT shininess;
	cadence::doste::OID BASEIMPORT shader;
	cadence::doste::OID BASEIMPORT texture;
	cadence::doste::OID BASEIMPORT textures;
	
	cadence::doste::OID BASEIMPORT clamp;
	cadence::doste::OID BASEIMPORT filename;
	cadence::doste::OID BASEIMPORT mipmap;
	cadence::doste::OID BASEIMPORT objects;
	cadence::doste::OID BASEIMPORT world;
	cadence::doste::OID BASEIMPORT positionvar;
	cadence::doste::OID BASEIMPORT rate;
	cadence::doste::OID BASEIMPORT life;
	cadence::doste::OID BASEIMPORT particles;
	cadence::doste::OID BASEIMPORT primitive;
	cadence::doste::OID BASEIMPORT primitives;
	cadence::doste::OID BASEIMPORT width;
	cadence::doste::OID BASEIMPORT height;
	cadence::doste::OID BASEIMPORT depth;
	cadence::doste::OID BASEIMPORT radius;
	cadence::doste::OID BASEIMPORT playing;
	cadence::doste::OID BASEIMPORT attenuation;
	cadence::doste::OID BASEIMPORT volume;
	cadence::doste::OID BASEIMPORT sounds;
	cadence::doste::OID BASEIMPORT sound;
	cadence::doste::OID BASEIMPORT velocity;
	cadence::doste::OID BASEIMPORT sprite;
	cadence::doste::OID BASEIMPORT sprites;
	cadence::doste::OID BASEIMPORT frame;
	cadence::doste::OID BASEIMPORT music;
	cadence::doste::OID BASEIMPORT number;
	cadence::doste::OID BASEIMPORT velocityvar;
	cadence::doste::OID BASEIMPORT growth;
	cadence::doste::OID BASEIMPORT growthvar;
	cadence::doste::OID BASEIMPORT endsize;
	cadence::doste::OID BASEIMPORT endsizevar;
	cadence::doste::OID BASEIMPORT startsize;
	cadence::doste::OID BASEIMPORT startsizevar;
	cadence::doste::OID BASEIMPORT lifevar;
	cadence::doste::OID BASEIMPORT fade;
	cadence::doste::OID BASEIMPORT fadevar;
	cadence::doste::OID BASEIMPORT startcolour;
	cadence::doste::OID BASEIMPORT startcolourvar;
	cadence::doste::OID BASEIMPORT endcolour;
	cadence::doste::OID BASEIMPORT endcolourvar;
	cadence::doste::OID BASEIMPORT acceleration;
	cadence::doste::OID BASEIMPORT accelerationvar;
	cadence::doste::OID BASEIMPORT resources;
	cadence::doste::OID BASEIMPORT vert;
	cadence::doste::OID BASEIMPORT frag;
	cadence::doste::OID BASEIMPORT shaders;
	cadence::doste::OID BASEIMPORT left;
	cadence::doste::OID BASEIMPORT right;
	cadence::doste::OID BASEIMPORT top;
	cadence::doste::OID BASEIMPORT bottom;
	cadence::doste::OID BASEIMPORT front;
	cadence::doste::OID BASEIMPORT back;
	cadence::doste::OID BASEIMPORT skybox;
	cadence::doste::OID BASEIMPORT skyboxes;
	cadence::doste::OID BASEIMPORT cur;
	cadence::doste::OID BASEIMPORT frames;
	cadence::doste::OID BASEIMPORT columns;
	cadence::doste::OID BASEIMPORT rows;
	cadence::doste::OID BASEIMPORT billboard;
	cadence::doste::OID BASEIMPORT distance;
	cadence::doste::OID BASEIMPORT atmosphere;
	cadence::doste::OID BASEIMPORT density;
	cadence::doste::OID BASEIMPORT camera;
	cadence::doste::OID BASEIMPORT fov;
	cadence::doste::OID BASEIMPORT far;
	cadence::doste::OID BASEIMPORT near;
	cadence::doste::OID BASEIMPORT zoom;
	cadence::doste::OID BASEIMPORT running;
	cadence::doste::OID BASEIMPORT flipped;
	cadence::doste::OID BASEIMPORT keyboard;
	cadence::doste::OID BASEIMPORT keys;
	cadence::doste::OID BASEIMPORT commands;
	cadence::doste::OID BASEIMPORT lighting;
	cadence::doste::OID BASEIMPORT smooth;
	cadence::doste::OID BASEIMPORT mouse;
	cadence::doste::OID BASEIMPORT deltax;
	cadence::doste::OID BASEIMPORT deltay;
	cadence::doste::OID BASEIMPORT buttons;
	cadence::doste::OID BASEIMPORT cursor;
	cadence::doste::OID BASEIMPORT colour;
	cadence::doste::OID BASEIMPORT window;
	cadence::doste::OID BASEIMPORT cube;
	cadence::doste::OID BASEIMPORT deltaz;
	cadence::doste::OID BASEIMPORT game;
	
	cadence::doste::OID BASEIMPORT scene;
	cadence::doste::OID BASEIMPORT levels;
	
	cadence::doste::OID BASEIMPORT instances;
	cadence::doste::OID BASEIMPORT instance2D;
	cadence::doste::OID BASEIMPORT instance3D;
	
	cadence::doste::OID BASEIMPORT resolutions;
	cadence::doste::OID BASEIMPORT clearcolour;
	cadence::doste::OID BASEIMPORT colourdepth;
	cadence::doste::OID BASEIMPORT depthbuffer;
	cadence::doste::OID BASEIMPORT title;
	cadence::doste::OID BASEIMPORT fullscreen;
	cadence::doste::OID BASEIMPORT movespeed;
	
	cadence::doste::OID BASEIMPORT paused;
	cadence::doste::OID BASEIMPORT blending;
	cadence::doste::OID BASEIMPORT resistance;
	cadence::doste::OID BASEIMPORT resistancevar;
	
	cadence::doste::OID BASEIMPORT axes;
	cadence::doste::OID BASEIMPORT compress;
	cadence::doste::OID BASEIMPORT controls;
	cadence::doste::OID BASEIMPORT scale;
	cadence::doste::OID BASEIMPORT value;
	cadence::doste::OID BASEIMPORT deadzone;
	cadence::doste::OID BASEIMPORT invert;
	
	cadence::doste::OID BASEIMPORT keep;
	cadence::doste::OID BASEIMPORT flipv;
	cadence::doste::OID BASEIMPORT fliph;
	cadence::doste::OID BASEIMPORT tint;
	cadence::doste::OID BASEIMPORT layer;
	cadence::doste::OID BASEIMPORT widgets;
	cadence::doste::OID BASEIMPORT caption;
	cadence::doste::OID BASEIMPORT grab;
	cadence::doste::OID BASEIMPORT focus;
	cadence::doste::OID BASEIMPORT parent;
	cadence::doste::OID BASEIMPORT screenx;
	cadence::doste::OID BASEIMPORT screeny;
	
	
	cadence::doste::OID BASEIMPORT volumes;
	cadence::doste::OID BASEIMPORT children;
	cadence::doste::OID BASEIMPORT light;
	cadence::doste::OID BASEIMPORT type;
	
	cadence::doste::OID BASEIMPORT glowfilename;
	cadence::doste::OID BASEIMPORT glowmax;
	cadence::doste::OID BASEIMPORT reload;
	cadence::doste::OID BASEIMPORT variables;
	cadence::doste::OID BASEIMPORT input;

	cadence::doste::OID BASEIMPORT source;
	cadence::doste::OID BASEIMPORT location;
	
	cadence::doste::OID BASEIMPORT time;
	};
};

void createIndices(){
	position = "position";
	orientation = "orientation";
	direction = "direction";
	changed = "changed";
	material = "material";
	materials = "materials"	;	
	model = "model";
	models = "models";
	animationset = "animationset";
	animations = "animations";
	animated = "animated";
	animation = "animation"	;
	transformed = "transformed";
	transition = "transition";
	meshes = "meshes";
	morphs = "morphs";
	morph = "morph";
	root = "root";
	bones = "bones";
	animset = "animset";
	start = "start";
	end = "end";
	fps = "fps";
	loop = "loop";
	next = "next";
	solid = "solid";
	mode = "mode";

	debug = "debug";
	
	x = "x";
	y = "y";
	z = "z";
	w = "w";
	r = "r";
	g = "g";
	b = "b";
	a = "a";
	sx = "sx";
	sy = "sy";
	sz = "sz";
	pitch = "pitch";
	yaw = "yaw";
	roll = "roll";

	console = "console";
	lines = "lines";
	ambient = "ambient";
	specular = "specular";
	diffuse = "diffuse";
	emission = "emission";
	directional = "directional";
	linear = "linear";
	quadratic = "quadratic";
	enabled = "enabled";
	lights = "lights";

	visible = "visible";
	showdebug = "showdebug";
	font = "font";
	bgcolour = "bgcolour";
	text = "text";
	size = "size";
	name = "name";
	bold = "bold";
	fonts = "fonts";

	shininess = "shininess";
	shader = "shader";
	texture = "texture";
	textures = "textures";

	clamp = "clamp";
	filename = "filename";
	mipmap = "mipmap";
	objects = "objects";
	world = "world";
	positionvar = "positionvar";
	rate = "rate";
	life = "life";
	particles = "particles";
	primitive = "primitive";
	primitives = "primitives";
	width = "width";
	height = "height";
	depth = "depth";
	radius = "radius";
	attenuation = "attenuation";
	volume = "volume";
	sounds = "sounds";
	playing = "playing";
	sound = "sound";
	velocity = "velocity";
	sprite = "sprite";
	sprites = "sprites";
	frame = "frame";
	music = "music";
	number = "number";
	velocityvar = "velocityvar";
	growth = "growth";
	growthvar = "growthvar";
	endsize = "endsize";
	endsizevar = "endsizevar";
	startsize = "startsize";
	startsizevar = "startsizevar";
	lifevar = "lifevar";
	fade = "fade";
	fadevar = "fadevar";
	startcolour = "startcolour";
	startcolourvar = "startcolourvar";
	endcolour = "endcolour";
	endcolourvar = "endcolourvar";
	acceleration = "acceleration";
	accelerationvar = "accelerationvar";
	resources = "resources";
	vert = "vert";
	frag = "frag";
	shaders = "shaders";
	wgd::ix::left = "left";
	wgd::ix::right = "right";
	top = "top";
	bottom = "bottom";
	front = "front";
	back = "back";
	skybox = "skybox";
	skyboxes = "skyboxes";
	cur = "cur";
	frames = "frames";
	columns = "columns";
	rows = "rows";
	billboard = "billboard";
	wgd::ix::distance = "distance";
	atmosphere = "atmosphere";
	density = "density";
	camera = "camera";
	fov = "fov";
	far = "far";
	near = "near";
	zoom = "zoom";
	running = "running";
	flipped = "flipped";
	keyboard = "keyboard";
	keys = "keys";
	commands = "commands";
	lighting = "lighting";
	smooth = "smooth";
	mouse = "mouse";
	deltax = "deltax";
	deltay = "deltay";
	buttons = "buttons";
	cursor = "cursor";
	colour = "colour";
	window = "window";
	cube = "cube";
	deltaz = "deltaz";
	game = "game";
	
	scene = "scene";
	levels = "levels";
	
	instances = "instances";
	instance2D = "Instance2D";
	instance3D = "Instance3D";

	resolutions = "resolutions";
	clearcolour = "clearcolour";
	colourdepth = "colourdepth";
	depthbuffer = "depthbuffer";
	title = "title";
	fullscreen = "fullscreen";
	movespeed = "movespeed";

	paused = "paused";
	blending = "blending";
	resistance = "resistance";
	resistancevar = "resistancevar";

	axes = "axes";
	compress = "compress";
	controls = "controls";
	scale = "scale";
	value = "value";
	deadzone = "deadzone";
	invert = "invert";

	keep = "keep";
	flipv = "flipv";
	fliph = "fliph";
	tint = "tint";
	layer = "layer";
	widgets = "widgets";
	caption = "caption";
	grab = "grab";
	focus = "focus";
	parent = "parent";
	screenx = "screenx";
	screeny = "screeny";
	
	volumes = "volumes";
	children = "children";
	type = "type";
	light = "light";

	glowfilename = "glowfilename";
	glowmax = "glowmax";
	reload = "reload";
	variables = "variables";
	input = "input";

	source = "source";
	location = "location";
	
	wgd::ix::time = "time";
}
